port: 7890
socks-port: 1080
redir-port: 7892
allow-lan: true

mode: rule

log-level: debug

dns:
 enable: true
 listen: 0.0.0.0:53
 enhanced-mode: redir-host
 nameserver:
   - 8.8.8.8
   - 223.5.5.5
   - 'tls://dns.rubyfish.cn:853'
 fallback:
   - 'tls://1.1.1.1:853'
   - 'tcp://1.1.1.1:53'
   - 'tcp://208.67.222.222:443'
   - 'tls://dns.google'
   - 'tls://dns.rubyfish.cn:853'
proxies:
  - name: "vmess"
    type: vmess
    server: {server}
    port: {port}
    uuid: {uuid}
    alterId: {alterId}
    cipher: auto
    # network: ws
rules:
  - DOMAIN-SUFFIX,google.com,vmess
  - DOMAIN-KEYWORD,google,vmess
  - MATCH,vmess